language: python
python:
  - "3.7"
install:
  - pip install coverage coveralls
  - pip install -r requirements.txt
  #- pip install -r test_requirements.txt
script:
  - coverage run --source=antelope_epa -m unittest
after_success:
  coveralls
